



POST http://127.0.0.1:8000/api/add_sensor/?name=VIKA&description=SSSSS
###

POST http://127.0.0.1:8000/api/sensor_update/?sensor_id=16&name=123123&desc=QQQQ
###

POST http://127.0.0.1:8000/api/add_measurement/?sensor_id=1&temp=100
###

GET http://127.0.0.1:8000/api/get_info_id/?sensor_id=16
###

GET http://127.0.0.1:8000/api/get_list_sensor/
###

GET http://127.0.0.1:8000/api/getget/
###






