

POST http://127.0.0.1:8000/api/add_measurement/?sensor_id=1&temp=100
###

GET http://127.0.0.1:8000/api/get_info_id/?sensor_id=16
###

GET http://127.0.0.1:8000/api/get_list_sensor/
###


POST http://127.0.0.1:8000/api/add_sensor/
Content-Type: application/json

{"sensor": {
  "name": "1111",
  "description": "1111"
}
}

###
PUT http://127.0.0.1:8000/api/sensor_update/24
Content-Type: application/json

{"sensor": {

  "description": "Получилось отредачить"
}
}

###





